### PR TITLE
docs: update environment setting

### PR DESCRIPTION
**Pull request by chisacam**
- It looks like the environment variable settings have not been updated in the development environment settings.
- So update the documentation to use the environment variable settings file as auto generated script.
- It is already mentioned above that customization of ports, etc. can be done in document, so we expect to have more flexibility when configuring and testing the development environment.
- This PR is a duplicate of [this](https://github.com/lablup/backend.ai-ossca-2023/pull/1) one, but I think it's better.

### CODE REVIEW

**Review by fregataa — COMMENTED** [review]
Thank you for PR!
This is a good suggestion to verify install step but I am not sure that whether deleting how to set environment variables is good or not.
How about just add two commented commands?

**Comment by chisacam** [comment]
I understand that you are suggesting to modify it as follows.

```bash
   export BACKEND_ENDPOINT=http://127.0.0.1:8091/  # change the port number if customized
   export BACKEND_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
   export BACKEND_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
   # source ./env-local-admin-api.sh # You can also use auto generated script!
   # source ./env-local-user-api.sh # Choose and use the environment you want.
   ./backend.ai config
   ./backend.ai run python -c 'print("hello world")'
   ∙ Session token prefix: fb05c73953
   ✔ [0] Session fb05c73953 is ready.
   hello world
   ✔ [0] Execution finished. (exit code = 0)
   ✔ [0] Cleaned up the session.
   ./backend.ai ps
```

However, if we need guide to environment variables, I think it would be sufficient to add a "note" as shown at document.

like this warning note for `install-dev.sh`.

```
...
Unless you customize all port numbers by the options of scripts/install-dev.sh, 
you should `docker compose -f docker-compose.halfstack.current.yml down` 
and `docker compose -f docker-compose.halfstack.current.yml up -d`
when switching between multiple working copies.
```

if we just change port number, when we change default port in `install-dev.sh`, we will change port in docs again.

that's why i think this way is better then just update port.

So, how about this way?

```bash
   source ./env-local-admin-api.sh # auto generate in project root if install-dev script was successful.
   # source ./env-local-user-api.sh # Choose and use the environment you want.
   ./backend.ai config
   ./backend.ai run python -c 'print("hello world")'
   ∙ Session token prefix: fb05c73953
   ✔ [0] Session fb05c73953 is ready.
   hello world
   ✔ [0] Execution finished. (exit code = 0)
   ✔ [0] Cleaned up the session.
   ./backend.ai ps
```

```markdown
.. note::
   These `env-local-*-api.sh` set the following environment variables in the shell.
   This is one of example automatically create as you not modify install-dev.sh.
   export BACKEND_ENDPOINT=http://127.0.0.1:8091/
   export BACKEND_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
   export BACKEND_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
   export BACKEND_ENDPOINT_TYPE=api
```

If just comment command is still good enough for reviewers, of course I'll just change it and commit.

**Comment by fregataa** [comment]
> So, how about this way?
> 
> ```shell
>    source ./env-local-admin-api.sh # auto generate in project root if install-dev script was successful.
>    # source ./env-local-user-api.sh # Choose and use the environment you want.
>    ./backend.ai config
>    ./backend.ai run python -c 'print("hello world")'
>    ∙ Session token prefix: fb05c73953
>    ✔ [0] Session fb05c73953 is ready.
>    hello world
>    ✔ [0] Execution finished. (exit code = 0)
>    ✔ [0] Cleaned up the session.
>    ./backend.ai ps
> ```
> 
> ```
> .. note::
>    These `env-local-*-api.sh` set the following environment variables in the shell.
>    This is one of example automatically create as you not modify install-dev.sh.
>    export BACKEND_ENDPOINT=http://127.0.0.1:8091/
>    export BACKEND_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
>    export BACKEND_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
>    export BACKEND_ENDPOINT_TYPE=api
> ```

Looks good for me! But let's not add any note or comment about other `env-*.sh` scripts because this is just one step to check whether the installation is successful or not.
And `# generated in project root if install-dev.sh worked correctly` seems more natural.
Please wait for other reviews!

**Review by fregataa — APPROVED** [review]
LGTM ! Thank you for your contribute.
Also, we add @hyoinandout because he contributed to the same issue.

**Pull request merged**
